#!/usr/bin/env python3
"""
Simple orchestrator to run the complete agentic security workflow.
Uses existing tools: llm_scanner, report_writer, ticket_writer
"""

import sys
import json
from pathlib import Path
from datetime import datetime

# Add project root to path
sys.path.append(str(Path(__file__).parent))

from tools.llm_scanner import LLMScanner
from tools.report_writer import ReportWriter
from tools.ticket_writer import TicketWriter
from tools.report_formatter import SecurityReportFormatter
from tools.coverage_analyzer import CoverageAnalyzer


def run_complete_workflow(repo_path: str, output_dir: str = "reports"):
    """Run the complete agentic security analysis workflow."""
    
    print("🚀 Starting Complete Agentic Security Workflow")
    print("=" * 60)
    print(f"📁 Repository: {repo_path}")
    print(f"💾 Output Directory: {output_dir}")
    print()
    
    # Step 1: Run AST-aware security analysis
    print("🔍 STEP 1: AST-Aware Security Analysis")
    print("-" * 40)
    scanner = LLMScanner()
    security_results = scanner.analyze_repository(repo_path, output_dir)
    print(f"✅ Security analysis complete: {len(security_results.get('findings', []))} findings")
    print()
    
    # Step 2: Generate comprehensive report
    print("📝 STEP 2: Generate Comprehensive Report")
    print("-" * 40)
    report_writer = ReportWriter()
    
    # Prepare report data
    report_data = {
        "repository": repo_path,
        "findings": security_results.get('findings', []),
        "metadata": security_results.get('analysis_metadata', {}),
        "summary": security_results.get('summary', {}),
        "timestamp": datetime.now().isoformat()
    }
    
    # Generate report
    report_file = Path(output_dir) / "comprehensive_security_report.json"
    report_writer.write_to_file(report_data, str(report_file))
    print(f"✅ Report generated: {report_file}")
    print()
    
    # Step 3: Generate security tickets
    print("🎫 STEP 3: Generate Security Tickets")
    print("-" * 40)
    ticket_writer = TicketWriter()
    
    # Generate tickets from findings
    tickets = ticket_writer.convert_findings_to_tickets(security_results)
    tickets_file = Path(output_dir) / "security_tickets.json"
    ticket_writer.write_tickets_to_file(tickets, str(tickets_file))
    print(f"✅ Tickets generated: {tickets_file}")
    print()
    
    # Step 4: Generate formatted reports (Text, Markdown, PDF)
    print("📄 STEP 4: Generate Formatted Reports")
    print("-" * 40)
    
    # Find the security analysis report generated by LLMScanner
    security_report_file = None
    for file_path in Path(output_dir).glob("**/security-analysis-report.json"):
        security_report_file = file_path
        break
    
    if security_report_file and security_report_file.exists():
        print(f"📋 Formatting report: {security_report_file}")
        formatter = SecurityReportFormatter(str(security_report_file))
        formatted_reports = formatter.generate_all_formats()
        
        print("✅ Formatted reports generated:")
        for format_type, path in formatted_reports.items():
            print(f"   {format_type.upper()}: {path}")
    else:
        print("⚠️  Security analysis report not found, skipping formatted reports")
    print()
    
    # Step 5: Coverage Analysis
    print("📊 STEP 5: Coverage Analysis")
    print("-" * 40)
    
    if security_report_file and security_report_file.exists():
        print(f"🔍 Analyzing coverage for: {repo_path}")
        coverage_analyzer = CoverageAnalyzer(repo_path, str(security_report_file))
        coverage_report_path = coverage_analyzer.save_coverage_report()
        print(f"✅ Coverage analysis complete: {coverage_report_path}")
        
        # Show coverage summary
        analysis = coverage_analyzer.analyze_coverage()
        metrics = analysis['coverage_metrics']
        print(f"📊 Coverage: {metrics['total_scanned_files']}/{metrics['total_repo_files']} files ({metrics['coverage_percentage']}%)")
    else:
        print("⚠️  Security analysis report not found, skipping coverage analysis")
    print()
    
    # Step 6: Summary
    print("🎉 AGENTIC WORKFLOW COMPLETE!")
    print("=" * 60)
    print(f"🔍 Security Findings: {len(security_results.get('findings', []))}")
    print(f"📝 Report: {report_file}")
    print(f"🎫 Tickets: {tickets_file}")
    
    # Show severity breakdown
    severity = security_results.get('summary', {}).get('severity_breakdown', {})
    if severity:
        print(f"\n📊 Severity Breakdown:")
        for level, count in severity.items():
            print(f"   {level}: {count}")
    
    # Show formatted reports if generated
    if security_report_file and security_report_file.exists():
        print(f"\n📄 Formatted Reports:")
        for format_type, path in formatted_reports.items():
            print(f"   {format_type.upper()}: {path}")
    
    return {
        "security_results": security_results,
        "report_file": report_file,
        "tickets_file": tickets_file,
        "formatted_reports": formatted_reports if 'formatted_reports' in locals() else {},
        "coverage_analysis": analysis if 'analysis' in locals() else {}
    }


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Run Complete Agentic Security Workflow")
    parser.add_argument("repo_path", help="Path to the repository to analyze")
    parser.add_argument("--output-dir", default="reports", help="Output directory for results")
    
    args = parser.parse_args()
    
    # Run the complete workflow
    results = run_complete_workflow(args.repo_path, args.output_dir)
